# Generated by Django 6.0.2 on 2026-03-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz_response',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
